[project]
name = "personal-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.28.2",
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "celery>=5.6.3",
    "dotenv>=0.9.9",
    "greenlet>=3.5.1",
    "langchain>=1.3.14",
    "langchain-cerebras>=0.8.2",
    "langgraph>=1.2.9",
    "pgvector>=0.5.0",
    "pillow>=12.3.0",
    "psycopg2-binary>=2.9.12",
    "pytesseract>=0.3.13",
    "redis>=8.0.1",
    "sqlalchemy>=2.0.50",
    "tzdata>=2026.3",
    "voyageai>=0.5.0",
]
